export class CurrentStockDetailsModel{
    currentStockDetailsId!:number;
    palletId!:number;
    coreSize!:string;
    palletCode!:string;
    palletCode1!:string; 
    palletInformationId!:number;
    productVariantCode!:string;
    productVariantCodeE2!:string;
    productId!:number;
    productName!:string;
    productVariantId!:number;
    productVariantName!:string;
    productVariantNameE2!:string;
    quantity!:number;
    positionId!:number;
    positionName!:string;
    positionNumberInRack!:number;
    positionIsActive!:number;
    emptyPalletPosition!:number;
    positionIsAllocatedForMission!:number;
    rackId!:number;
    rackName!:string;
    rackSide!:string;
    rackColumn!:number;
    rackIsActive!:number;
    rackIsEmpty!:number;
    floorId!:number;
    floorName!:string;
    floorIsActive!:number;
    areaId!:number;
    areaName!:string;
    loadDatetime!:string;
    isOutfeedMissionGenerated!:number;
    isInfeeddMissionGenerated!:number;
    engien1Code!:string;
    engien2Code!:string;
    palletType!:string;
    engine1Weight!:number;
    engine2Weight!:number;
    batchNumber!:string;
    modelNumber!:string;
    modelNumberE2!:string;
    location!:string;
    palletStatusName!:string;
    palletStatusId!:number;
    ageingDays!:number;
    serialNoStartingChar!:string;
    nomenclature!:string;
    isDispatched: boolean = false;
    coreShop!:string;
    userId!:number;
    userName!:string;
  // totalQuantity: any;

 
}
